### ISSUE TITLE
New GPT submission: Lore Master

### ISSUE THREAD

**Issue by joenb33** [ai-boost/Awesome-GPTs#10]
A GPTs that love to discuss, explain and dive in to the rabbit hole of lore and Easter eggs of games and movies: 

https://chat.openai.com/g/g-i2DASMYiX-lore-master

**Comment by ai-boost** [comment]
Hi, thanks for your GPT🌟!  Which category should this GPT be placed under, hmm? 🤔💭

**Comment by ai-boost** [comment]
Now we have Productivity, Writing, Programming, Education, Just for Fun, 5 categories.

If it is special, we can create new categories.😊

**Comment by joenb33** [comment]
I guess it is "just for fun". Or if it feels okay to create a new one, like "Informational", "Educational" or something like that?

**Comment by ai-boost** [comment]
After deeply experiencing the Lore Master GPT, I've come to see that it's not just for fun. It has a depth of knowledge, so I'm categorizing it under Education. 🏫

Thanks a ton for making Lore Master! 🌈 I'm eager for your future enhancements and hope it can make a difference for many.

**Comment by ai-boost** [comment]
Already added the GPT to Awesome-GPTs🎉

---
This GitHub repository is still a bit of a hidden gem💎, and I'm hoping you can help spread the repo to the community or your friends. It's really important.❤️

**Comment by ai-boost** [comment]
Dear joenb33,

Your awesome GPT has added in Awesome-GPTs🥳🥳🥳

Thank you so much for your kind words and invaluable contribution! 😊 Your dedication and effort in crafting such a wonderful GPT for our repository are deeply appreciated.
We fully recognize and value the time and expertise you have shared with us. Your work has not only enriched our project but also inspired the community. ✨ 
Please know that you are always welcome to reopen this issue whenever you need or wish to contribute further. We're here to support and collaborate with you at any time.

Also, a big thank you for your **stars**🌟and for helping to **spread the word**🔥 about our work. Your support means a lot to us and helps in fostering a collaborative and thriving community. 🙌
Looking forward to our continued collaboration and mutual growth. Stay amazing!

Warm regards,
Awesome-GPTs🦄
