### ISSUE TITLE
AI Comic Maker: Create Comics using ChatGPT

### ISSUE THREAD

**Issue by eliohead** [ai-boost/Awesome-GPTs#105]
A GPT to create comics using ChatGPT and DALL-E, trying to mantain consistency of characters and images. 

[https://chat.openai.com/g/g-1LM0T9LSW-ai-comic-maker](https://chat.openai.com/g/g-1LM0T9LSW-ai-comic-maker)

**Comment by ai-boost** [comment]
Hi, nice Comic GPT, thanks~ I'll add this!

**Comment by ai-boost** [comment]
Added 🎉, thanks!

**Comment by ai-boost** [comment]
Hi eliohead,

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs
