### ISSUE TITLE
YouTubeGPT - Summarize and chat with YouTube videos

### ISSUE THREAD

**Issue by m1guelpf** [ai-boost/Awesome-GPTs#106]
A GPT that can get transcripts for any YouTube video to interact with its content.

https://chat.openai.com/g/g-VgadmpesQ-youtubegpt

**Comment by ai-boost** [comment]
Cool, I'll add this!

**Comment by ai-boost** [comment]
Already added the GPT to Awesome-GPTs🎉

By the way, this GitHub repository is still a bit of a hidden gem💎, and I'm hoping you can help spread the repo to the community or your friends. It's really important.❤️
