### ISSUE TITLE
New GPT Submission: Poe Bot Creator

### ISSUE THREAD

**Issue by eseuz** [ai-boost/Awesome-GPTs#107]
🤖 Poe Bot Creator

- A GPT that can help you create a chatbot at Poe
- https://chat.openai.com/g/g-E0BtBRrf5-poe-bot-creator
- Productivity

**Comment by ai-boost** [comment]
Thanks! Nice GPT!

**Comment by ai-boost** [comment]
The Poe Bot GPT has been added to Productivity category🎉. See commit: https://github.com/ai-boost/Awesome-GPTs/commit/0a0dcbac7dd1577b09c159fb5eb06de1e53c08fa

**Comment by eseuz** [comment]
Thank you 😊
