### ISSUE TITLE
Quicksense: Qliksense code and data viz assistant

### ISSUE THREAD

**Issue by h4k44n** [ai-boost/Awesome-GPTs#108]
1. 🍭 Quicksense
   - Qliksense code and data viz assistant
   - [Chat now](https://chat.openai.com/g/g-8EvOF8yGH-quicksense-by-1skeml3.)
   - Submit by [@H4K4N](https://github.com/h4k44n)

**Comment by ai-boost** [comment]
Hi, thanks for your awesome GPT, I will add this soon! 🎉

**Comment by h4k44n** [comment]
> Hi, thanks for your awesome GPT, I will add this soon! 🎉

Tnx, but plz check. 

Quicksense: Qliksense code and data viz assistant, 

not 

Quicksense: **_Quicksense_** code and data viz assistant

**Comment by ai-boost** [comment]
My fault🙏 Thanks for your PR😊

**Comment by h4k44n** [comment]
> My fault🙏 Thanks for your PR😊

No problem, but still false :'( 
İt's Qlik sense, not Qlicksense. Tnx again.

**Comment by ai-boost** [comment]
Hi, I just copy your GPT description from your GPT link. Please take a look, is it correct now?

**Comment by h4k44n** [comment]
> Hi, I just copy your GPT description from your GPT link. Please take a look, is it correct now?

Thank you very much

**Comment by ai-boost** [comment]
Hi 👋,

Thank you so much for your kind words and invaluable contribution! 😊 Your dedication and effort in crafting such a wonderful GPT for our repository are deeply appreciated.
We fully recognize and value the time and expertise you have shared with us. Your work has not only enriched our project but also inspired the community. ✨ 
Please know that you are always welcome to reopen this issue whenever you need or wish to contribute further. We're here to support and collaborate with you at any time.

Also, a big thank you for your **stars**🌟and for helping to **spread the word**🔥 about our work. Your support means a lot to us and helps in fostering a collaborative and thriving community. 🙌
Looking forward to our continued collaboration and mutual growth. Stay amazing!

Warm regards,
Awesome-GPTs🦄
