### ISSUE TITLE
New GPT Submission: DrinkinGPT

### ISSUE THREAD

**Issue by FabKremer** [ai-boost/Awesome-GPTs#11]
Unveiling [DrinkinGPT](https://chat.openai.com/g/g-WiovsNXf1-drinkingpt) - your go-to for crafting the ultimate drinking games! 🚀 Whether you've got dice, cards, or just a bunch of cups, DrinkinGPT tailors games perfectly to your group's vibe.

Here's how it rolls:
1. 🤔 Ask Away: DrinkinGPT hits you with simple questions - think resources, number of players, game length (5, 10, or 15 mins), and how adventurous you're feeling with your drinks.
2. 🎯 Custom Games: Based on your answers, you get a game that's just right, mixing luck, skill, and loads of laughs.
3. 🍸 Safe Sipping: Each game is designed for personal cup use - because safety can be fun too!

Ping me if you have any feedback / comments!

**Comment by ai-boost** [comment]
I think this should be put under the category of productivity tools, what do you think?🤔

**Comment by FabKremer** [comment]
Well, I think it's a "productivity tool" in a way that it helps organize and suggest drinking games, but I feel it's also "just for fun" purposes. I'll leave it in your hands! It's kind of the same for me 🙂

**Comment by ai-boost** [comment]
Already added the GPT to Awesome-GPTs🎉
Thanks for your genius job😊

---
This GitHub repository is still a bit of a hidden gem💎, and I'm hoping you can help spread the repo to the community or your friends. It's really important.❤️

**Comment by ai-boost** [comment]
Dear FabKremer,

Your awesome GPT has added in Awesome-GPTs🥳🥳🥳

Thank you so much for your kind words and invaluable contribution! 😊 Your dedication and effort in crafting such a wonderful GPT for our repository are deeply appreciated.
We fully recognize and value the time and expertise you have shared with us. Your work has not only enriched our project but also inspired the community. ✨ 
Please know that you are always welcome to reopen this issue whenever you need or wish to contribute further. We're here to support and collaborate with you at any time.

Also, a big thank you for your **stars**🌟and for helping to **spread the word**🔥 about our work. Your support means a lot to us and helps in fostering a collaborative and thriving community. 🙌
Looking forward to our continued collaboration and mutual growth. Stay amazing!

Warm regards,
Awesome-GPTs🦄
