### ISSUE TITLE
New GPTs Submit: From Another Time

### ISSUE THREAD

**Issue by CeamKrier** [ai-boost/Awesome-GPTs#112]
⏳ From Another Time 
   - Talk to anyone, visit a place, past or future.
   - [Chat now](https://chat.openai.com/g/g-sg5h7XuWn-from-another-time)

Can be under the fun section

**Comment by ai-boost** [comment]
Thanks, an insteresting GPT, I will add this!

**Comment by ai-boost** [comment]
The awesome From Another Time GPT has been added to Awesome-GPTs🎉
