### ISSUE TITLE
New GPTs Submit: OCR

### ISSUE THREAD

**Issue by docduo** [ai-boost/Awesome-GPTs#116]
1. OCR
   - AI assistant to extract text from images and pdf documents.
   - [Chat now](https://chat.openai.com/g/g-wETMBcESv-ocr)
   - Submit by [@docduo](author profile link)

**Comment by ai-boost** [comment]
Thanks, I will add this under Productivity category

**Comment by ai-boost** [comment]
The awesome GPT has been added to Awesome-GPTs🎉

**Comment by ai-boost** [comment]
Hi 👋,

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs🦄
