### ISSUE TITLE
New GPTs Submit: DJGPT

### ISSUE THREAD

**Issue by HeyitsRadinn** [ai-boost/Awesome-GPTs#118]
🎧 DJGPT
   - I'm DJGPT, your go-to AI for all things DJing and music mixing, here to guide you through the exciting world of beats and tracks!
   - [Chat now](https://chat.openai.com/g/g-NlwIQ4CSj-djgpt.)
   - Submit by [@HeyitsRadinn](https://github.com/HeyitsRadinn)

**Comment by ai-boost** [comment]
Thanks, I will add this!🎉
