### ISSUE TITLE
Dr. Andrew Huberman GPT: Does not recall knowledge source

### ISSUE THREAD

**Issue by hokarangen** [ai-boost/Awesome-GPTs#12]
The Dr. Andrew Huberman GPT does not seem to recall what it has been trained on. I asked questions surrounding topics he has brought up in his episodes but it seems to only output generic answers with no correlation to the actual answers provided by Andrew Huberman.

**Comment by ai-boost** [comment]
Hi, thanks for your suggestion😊, I will contact the GPT author to fix this, see: [issue 7](https://github.com/ai-boost/Awesome-GPTs/issues/7)

**Comment by hokarangen** [comment]
Thank you for your effort and great work, it has been improved and outputs better answers now!
