### ISSUE TITLE
New GPTs Submit: Different GPTs

### ISSUE THREAD

**Issue by Master-of-secrets** [ai-boost/Awesome-GPTs#126]
1. Pet Health Companion
   - Adaptable, friendly virtual vet
   - [Chat now](https://chat.openai.com/g/g-xcffQ34CX-pet-health-companion)
2. Allergy Sidekick
-Rapid, baseline-knowledge allergy aid for millennials and Gen Z.
-[Chat now](https://chat.openai.com/g/g-zYcH7fzIN-allergy-sidekick)
3. Bedtime Stories
-Adventurous storyteller for kids.
-[Chat now](https://chat.openai.com/g/g-2B9b3hNRn-bedtime-stories)
4. Product Pathfinder
-Guides through product discovery, crafts PRDs
-[Chat now](https://chat.openai.com/g/g-nm2Kowg4B-product-pathfinder)
5. Motherhood Guide
-Warm, comforting advisor for moms-to-be and new mothers.
-[Chat now](https://chat.openai.com/g/g-mYedAIWt0-motherhood-guide)
6. Jigsaw's Gambit
-Mysterious narrative game channeling Jigsaw's essence.
-[Chat now](https://chat.openai.com/g/g-dOCQGSOQ5-jigsaw-s-gambit)

**Comment by ai-boost** [comment]
Hi, which GPT do you perfer? 🤔

**Comment by Master-of-secrets** [comment]
Do you prefer for me to open a issue for each of them?

**Comment by Master-of-secrets** [comment]
You can put the first one and i can add the others in new issues. Is that ok for you?

**Comment by ai-boost** [comment]
> You can put the first one and i can add the others in new issues. Is that ok for you?

A PR is perfered, thanks! Also, don't forget to sign your name😊

**Comment by Master-of-secrets** [comment]
Sorry, i will do that. ;) You can clsoe this one and i will create one for each. And sign my name
