### ISSUE TITLE
New GPTs Submit: various GPTs by GPTDuel

### ISSUE THREAD

**Issue by GPTDuel** [ai-boost/Awesome-GPTs#128]
1. ⭐ GPT Duel Simulator
   - An epic duel simulator between any two [anime/movies/video games] characters you can think of 
   - [Chat now](https://chat.openai.com/g/g-qYjcndY2u-gpt-duel-simulator)
   - Submit by [@GPTDuel](https://github.com/GPTDuel) 
2. 👩 Rin-chan
   - Chat with Rin (a girl who aspires to be a singer and even has her own schedule!) 
   - [Chat now](https://chat.openai.com/g/g-RiFAwSVeD-rin-chan)
   - Submit by [@GPTDuel](https://github.com/GPTDuel) 
3. 🍟 Anime Trivia
   - Your friendly anime trivia expert 
   - [Chat now](https://chat.openai.com/g/g-JzIxwuYF1-anime-trivia)
   - Submit by [@GPTDuel](https://github.com/GPTDuel) 
4. ❓ Riddle Master
   - Can you solve this riddle? 
   - [Chat now](https://chat.openai.com/g/g-j4iyVfj6M-riddle-master)
   - Submit by [@GPTDuel](https://github.com/GPTDuel)

**Comment by ai-boost** [comment]
Thanks, I'll add the 4 GPTs. Please keep updated and maintained, thanks for your nice GPTs!

**Comment by GPTDuel** [comment]
Awesome! Thank you. I will keep them updated!

**Comment by ai-boost** [comment]
Hi 👋,

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs🦄
