### ISSUE TITLE
New GPTs Submit: Github Public Repo assistant

### ISSUE THREAD

**Issue by thesamir** [ai-boost/Awesome-GPTs#129]
Github Repo Assistant
   - Provides both general and specific guidance on publicly accessible Github Repositories and their contents.
   - [Try it now](https://chat.openai.com/g/g-QA3Dl6r3G-repo-assistant)

**Comment by ai-boost** [comment]
Thanks, I'll add this GPT!

**Comment by ai-boost** [comment]
Added!

**Comment by ai-boost** [comment]
Hi 👋,

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs🦄
