### ISSUE TITLE
New GPTs Submit: SourceGPT

### ISSUE THREAD

**Issue by thesamir** [ai-boost/Awesome-GPTs#132]
1. SourceGPT
   - A (joke) GPT that disguises itself as a helpful source finder, but will always return a link to a rick roll video.
   -    - [Chat now](https://chat.openai.com/g/g-yRhodZ91O-source-gpt)
   - Submit by me

**Comment by ai-boost** [comment]
I'll add this. Thx!

**Comment by ai-boost** [comment]
Added! 🙂

**Comment by ai-boost** [comment]
Hi 👋,

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs🦄
