### ISSUE TITLE
UpScaler: GPT to create and upscale/de-noise Dalle images

### ISSUE THREAD

**Issue by weisshb** [ai-boost/Awesome-GPTs#139]
[UpScaler ](https://chat.openai.com/g/g-ikwGM4grU-upscaler) is a specialized version of ChatGPT that focuses on enhancing and upscaling images created through Dall-E. Its primary function is to take images generated in a Dalle session and upscale them to larger resolutions, making them suitable for various applications, such as printing or digital display at higher quality. It also supports optional abbreviations to make image generation easier.

https://chat.openai.com/g/g-ikwGM4grU-upscaler

**Comment by ai-boost** [comment]
I'll add this. Thx!

**Comment by ai-boost** [comment]
Hi 👋,

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs🦄
