### ISSUE TITLE
New GPTs Submit: Galactic Reckoning: A Star Wars GPT Game

### ISSUE THREAD

**Issue by LaneBucher** [ai-boost/Awesome-GPTs#144]
🌌 Galactic Reckoning: A Star Wars GPT Game (Lore Accurate)
   - A GPT Game putting you in the Star Wars Universe, create your character, choose your era, and make your place in the Galaxy!
   - [Chat now](https://chat.openai.com/g/g-9KZ1LXOcN-galactic-reckoning-a-star-wars-gpt-game)

**Comment by ai-boost** [comment]
I'll add this. Thx!

**Comment by ai-boost** [comment]
Added🎉

**Comment by ai-boost** [comment]
Hi 👋,

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs🦄
