### ISSUE TITLE
New GPTs Submit: PC Builder GPT

### ISSUE THREAD

**Issue by HeyitsRadinn** [ai-boost/Awesome-GPTs#146]
🖥️ PC Builder GPT
   - I'm PC Builder GPT, your tech-savvy virtual friend who offers expert and approachable advice on building PCs, complete with up-to-date pricing.
   - [Chat now](https://chat.openai.com/g/g-gh7PDdmmd-pc-builder-gpt)
   - Submit by [@HeyitsRadinn](https://github.com/HeyitsRadinn)

**Comment by ai-boost** [comment]
I'll add this. Thx!

**Comment by ai-boost** [comment]
Added! 🎉

**Comment by ai-boost** [comment]
Hi 👋,

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs🦄
