### ISSUE TITLE
New GPTs Submit:  U.S. Tax Helper

### ISSUE THREAD

**Issue by JayCoin6084** [ai-boost/Awesome-GPTs#149]
Thank you for your contributions!🦄

1. U.S. Tax Helper
   - A multilingual tax expert to handle all of your tax questions. 
   - [Chat now](https://chat.openai.com/g/g-iuqYldlaB-u-s-tax-help)
   - Submit by [@jaycoin6084](https://github.com/JayCoin6084) 

an example:

1. 💻Professional Coder (Auto programming)
   - A gpt expert at solving programming problems, automatic programming, one-click project generation
   - [Chat now](https://chat.openai.com/g/g-HgZuFuuBK-professional-coder-auto-programming)
   - Submit by [@ai-boost](https://github.com/ai-boost)

**Comment by ai-boost** [comment]
I'll add this. Thx!

**Comment by ai-boost** [comment]
Added🎉!

**Comment by ai-boost** [comment]
Hi 👋,

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs🦄
