### ISSUE TITLE
New GPTs Submit: Document Generator

### ISSUE THREAD

**Issue by JasonLLu** [ai-boost/Awesome-GPTs#150]
1. 📄 PDF/DocX Generator
   -Generate any complex documents, worksheets, charts, tables etc. in PDF or DocX format powered by LaTeX
   - [Chat now](https://chat.openai.com/g/g-0gbxqCG1B-document-generator)
   - Submit by [@gpt2office](www.gpt2office.com)

**Comment by ai-boost** [comment]
Thanks, I'll add this!

**Comment by ai-boost** [comment]
Added🎉

**Comment by ai-boost** [comment]
Hi 👋,

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs🦄
