### ISSUE TITLE
New GPTs Submit: Find a Design Agency & UX Design Coach

### ISSUE THREAD

**Issue by dylandeheer** [ai-boost/Awesome-GPTs#154]
1. Find a Design Agency
   - A gpt to help you find a design agency in your vicinity based on your design needs
   - [Chat now](https://chat.openai.com/g/g-IOyxoYe5T-find-a-design-agency)
   - Submit by [@dylandeheer](https://github.com/dylandeheer)
2. UX Design Coach
   - A gpt to help you navigate the vast landscape of design challenges, ask anything about visual design, user research, human psychology and more
   - [Chat now](https://chat.openai.com/g/g-L3KX57hjg-ux-design-coach)
   - Submit by [@dylandeheer](https://github.com/dylandeheer)

**Comment by ai-boost** [comment]
I'll add this. Thx!

**Comment by ai-boost** [comment]
Added 🎉

**Comment by ai-boost** [comment]
Hi 👋,

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs🦄
