### ISSUE TITLE
New GPT submisson: A BA that creates user stories

### ISSUE THREAD

**Issue by MathewBeldon** [ai-boost/Awesome-GPTs#17]
It will take a short input from the user, ask clarifying questions and then create a user story with acceptance criteria. 

https://chat.openai.com/g/g-kmEXnBMZY-bob-the-ba-user-story

https://chat.openai.com/share/bcaaad81-7f62-4726-9c99-ceda723bd81a

**Comment by ai-boost** [comment]
Hi, thanks for your contribution.😊

But OpenAI website give me an error message: "GPT inaccessible or not found" (first link)

There must be some mistakes here, can you help me figure it out?

**Comment by MathewBeldon** [comment]
Should be working, I've republished hopefully that will sort it

**Comment by MathewBeldon** [comment]
> Hi, thanks for your contribution.😊
> 
> But OpenAI website give me an error message: "GPT inaccessible or not found" (first link)
> 
> There must be some mistakes here, can you help me figure it out?

Has the republish sorted it?

**Comment by ai-boost** [comment]
It is work very well, thanks for your brilliant work~❤️

I'll add this soon🎉
