### ISSUE TITLE
New GPTs Submit: Nutri Tracker

### ISSUE THREAD

**Issue by clk1st** [ai-boost/Awesome-GPTs#170]
1. Nutri Tracker
   - Strict and formal dietary supervisor for detailed calorie tracking.
   - [Chat now](https://chat.openai.com/g/g-7cFbGmQHq-nutri-tracker)
   - Submit by [@synthmind.app](https://synthmind.app/?89991) 
2. Corporate Explorer
   - I source high-quality corporate data.
   - [Chat now](https://chat.openai.com/g/g-lVvQdvz9s-corporate-explorer)
   - Submit by [@synthmind.app](https://synthmind.app/?89992)

**Comment by ai-boost** [comment]
Thx, I'll add this!

**Comment by ai-boost** [comment]
Hi 👋,

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs🦄
