### ISSUE TITLE
New GPTs Submit (2 included)

### ISSUE THREAD

**Issue by benhurley** [ai-boost/Awesome-GPTs#195]
Thank you in advance!

1. 🎮 Game Genius
   - Your go-to expert for gameplay walkthroughs and cheat codes.
   - [Chat now](https://chat.openai.com/g/g-12q0jqkhd-game-genius)
   - Submit by [@benhurley](https://github.com/benhurley) 
2. 🍷 Vinobot
   - Digital sommelier for specific wine bottle recommendations.
   - [Chat now](https://chat.openai.com/g/g-EoBW5i2gu-vinobot)
   - Submit by [@benhurley](https://github.com/benhurley)

**Comment by ai-boost** [comment]
Thx, I'll add the 2 GPTs😊

**Comment by ai-boost** [comment]
Added🎉
