### ISSUE TITLE
New GPT Submission: Lorekeeper

### ISSUE THREAD

**Issue by cameronsevern** [ai-boost/Awesome-GPTs#2]
https://chat.openai.com/g/g-jTSN6CrPW-lorekeeper

This GPT plays the role of a dungeon master, story teller, or character creator for your next epic adventure. It is instructed to lean on image generation for telling immersive stories. It is also well versed in the rules of popular tabletop games.

**Comment by ai-boost** [comment]
Okay, thanks. I'll put it in. 

This GitHub repository is still a bit of a hidden gem💎, and I'm hoping you can help spread the word to the community. It's really important.❤️

**Comment by ai-boost** [comment]
> https://chat.openai.com/g/g-jTSN6CrPW-lorekeeper
> 
> This GPT plays the role of a dungeon master, story teller, or character creator for your next epic adventure. It is instructed to lean on image generation for telling immersive stories. It is also well versed in the rules of popular tabletop games.

Awesome GPT, so much fun! 🎉 Already added it to Awesome-GPTs, can't wait for future masterpieces.

**Comment by ai-boost** [comment]
Dear cameronsevern,

Your awesome GPT has added in Awesome-GPTs🥳🥳🥳

Thank you so much for your kind words and invaluable contribution! 😊 Your dedication and effort in crafting such a wonderful GPT for our repository are deeply appreciated.
We fully recognize and value the time and expertise you have shared with us. Your work has not only enriched our project but also inspired the community. ✨ 
Please know that you are always welcome to reopen this issue whenever you need or wish to contribute further. We're here to support and collaborate with you at any time.

Also, a big thank you for your **stars**🌟and for helping to **spread the word**🔥 about our work. Your support means a lot to us and helps in fostering a collaborative and thriving community. 🙌
Looking forward to our continued collaboration and mutual growth. Stay amazing!

Warm regards,
Awesome-GPTs🦄
