### ISSUE TITLE
New GPT Submission: Trivia Bot

### ISSUE THREAD

**Issue by moutonf** [ai-boost/Awesome-GPTs#23]
🧩Trivia Bot
   - A GPT to help you create your own Trivia quiz or just spend some time answering questions.
   - [Chat now](https://chat.openai.com/gpts/editor/g-mkdJHpJ2U)
   - Submit by [@moutonf](https://github.com/moutonf)

**Comment by ai-boost** [comment]
Thanks for your PR, this helped the repo a lot🥂

**Comment by ai-boost** [comment]
Hi moutonf,

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs
