### ISSUE TITLE
New GPTs Submit: SpotifyGPT

### ISSUE THREAD

**Issue by HeyitsRadinn** [ai-boost/Awesome-GPTs#254]
1. 🎧SpotifyGPT
   - Introducing SpotifyGPT, your ultimate music companion powered by AI, ready to curate playlists, recommend songs, and engage in music-inspired conversations.
   - [Chat Here](https://chat.openai.com/g/g-fVNPc64Pe-spotifygpt)
   - Submit by [@HeyitsRadinn](https://github.com/HeyitsRadinn)

**Comment by ai-boost** [comment]
Added! 🎉
