### ISSUE TITLE
New GPTs Submit: 🦀️ Rust Assistant

### ISSUE THREAD

**Issue by gengteng** [ai-boost/Awesome-GPTs#258]
1. 🦀️ Rust Assistant
   - Your go-to expert in the Rust ecosystem, specializing in precise code interpretation, up-to-date crate version checking, and in-depth source code analysis. I offer accurate, context-aware insights for all your Rust programming questions.
   - repo: https://github.com/gengteng/rust-assistant
   - [Chat now](https://chat.openai.com/g/g-u1O5yxYeW-rust-assistant)
   - Submit by [@GengTeng](https://github.com/gengteng)

**Comment by gengteng** [comment]
@ai-boost

**Comment by ai-boost** [comment]
Added 🎉!
