### ISSUE TITLE
New GPT Submission: h4ckGPT

### ISSUE THREAD

**Issue by 0xn0v** [ai-boost/Awesome-GPTs#3]
### h4ckGPT: Your personal security tool
---
I publised [h4ckGPT ](https://chat.openai.com/g/g-1ehIO0APO-h4ckgpt)as starter to assist myself & others in:

- Security Research
- Penetration Testing Techniques
- Application Security
- News & Updates, etc.

_I'm a security professional and have found ChatGPT to be a great resource in assisting me during Capture-The-Flags (CTFs) & live engagements :)_

As always, please avoid submitting sensitive inputs, and ensure you have the necessary consent from the targets you test!

h4ppy h4cking!
-- 0xn0v

**Comment by ai-boost** [comment]
Alrighty, looks great! 🌟 I'll add this GPT to the list.

**Comment by ai-boost** [comment]
Already added it to Awesome-GPTs.

---
By the way:

This GitHub repository is still a bit of a hidden gem💎, and I'm hoping you can help spread the word to the community. It's really important.❤️

**Comment by ai-boost** [comment]
Dear 0xn0v,

Your awesome GPT has added in Awesome-GPTs🥳🥳🥳

Thank you so much for your kind words and invaluable contribution! 😊 Your dedication and effort in crafting such a wonderful GPT for our repository are deeply appreciated.
We fully recognize and value the time and expertise you have shared with us. Your work has not only enriched our project but also inspired the community. ✨ 
Please know that you are always welcome to reopen this issue whenever you need or wish to contribute further. We're here to support and collaborate with you at any time.

Also, a big thank you for your **stars**🌟and for helping to **spread the word**🔥 about our work. Your support means a lot to us and helps in fostering a collaborative and thriving community. 🙌
Looking forward to our continued collaboration and mutual growth. Stay amazing!

Warm regards,
Awesome-GPTs🦄

**Comment by 0xn0v** [comment]
Thank you so much! Will share the repo on my twitter :)
