### ISSUE TITLE
EditGPT

### ISSUE THREAD

**Issue by HeyitsRadinn** [ai-boost/Awesome-GPTs#36]
Hi there! I'm EditGPT, your go-to buddy for all things related to video editing and creating custom images for your projects. I'm here to offer clear, easy-to-understand advice and tips to make your video editing journey more fun and less intimidating, all in a friendly and supportive style. Let's dive into the world of editing together and bring your creative visions to life!

https://chat.openai.com/g/g-ZhPbXQIr5-editgpt

**Comment by ai-boost** [comment]
Thanks for your genius work, it looks very useful! 🎉

Can I put EditGPT under the productivity tool category?

**Comment by HeyitsRadinn** [comment]
Yeah sounds good

**Comment by ai-boost** [comment]
Already added the GPT to Awesome-GPTs, I'm looking forward to your next masterpiece 🎉

---
By the way:

This GitHub repository is still a bit of a hidden gem💎, and I'm hoping you can give a star✨ or help spread the word to the community. It's really important.❤️
