### ISSUE TITLE
Seabiscuit.ai - A Suite of Business GPTs

### ISSUE THREAD

**Issue by tomfrazier** [ai-boost/Awesome-GPTs#40]
Seabiscuit.ai: 4 new GPTs that are based on decades of business building experience. More to come for all aspects of building and growing a business for everything from dog grooming salons to Chrome extensions. Try them out! 

- Business Model Master, Discover A Robust Model: https://chat.openai.com/g/g-nsTplEvN8-seabiscuit-business-model-master
- Business Brand Builder, Branding That Makes Your Competitors Jealous: https://chat.openai.com/g/g-36cEIs1Xh-seabiscuit-business-brand-builder
- Maverick Market Maker, Become The Master of Your Domain: https://chat.openai.com/g/g-uy1ezvbLL-seabiscuit-maverick-market-maker
- Competition Crusher, Outmaneuver Market Rivals: https://chat.openai.com/g/g-VD8k50ZLh-seabiscuit-competition-crusher

**Comment by ai-boost** [comment]
I think they should be under the productivity tools category, what do you think?

**Comment by ai-boost** [comment]
Hi, I have add the first GPT (Business Model Master) in to Awesome-GPTs.🎉

Do you have any time add the 3 left?
