### ISSUE TITLE
New GPT submission: Critical thinker

### ISSUE THREAD

**Issue by greencat667** [ai-boost/Awesome-GPTs#43]
Work through any problem in a 3 step process:
https://chat.openai.com/g/g-1KHebYbFR-critical-thinker

Critical thinker will ask follow up questions, create options and finally critique those options to identify the best one.

Example: What book should I read next?
https://chat.openai.com/share/ee4647c7-b2f8-490c-a43c-06ba8f457923

**Comment by ai-boost** [comment]
Hello there! 👋
I've seen you've submitted a bunch of GPTs, and that's just awesome! 🌟
Would you like to make a PR? Let's build this Awesome-GPT repo together! 🚀🤝

**Comment by greencat667** [comment]
Will try, I've never done a pull request before!?

**Comment by ai-boost** [comment]
Cool
