### ISSUE TITLE
New GPT Submission: Spicy Question Master

### ISSUE THREAD

**Issue by SimonDeno** [ai-boost/Awesome-GPTs#44]
🌶️  Spicy Question master 🌶️ (Have an interesting evening with friends)

You know when you're in a group and you want to play something like truth or dare or most likely to but nobody can find any good questions - Try this question master to get inspiration and ask questions like a game show host and you can tune it up to ask for it to be more/less spicy

[Chat Now](https://chat.openai.com/g/g-AcPoggC0T-spicy-questionmaster)

Link: https://chat.openai.com/g/g-AcPoggC0T-spicy-questionmaster

**Comment by ai-boost** [comment]
Hi, the Spicy🌶️ is really insteresting, I'll add this awesome GPT😊!

**Comment by ai-boost** [comment]
The Spicy GPT has been add to the Awesome-GPTs list, thanks for your contribution 🎉

By the way: this GitHub repository is still a bit of a hidden gem, and I'm hoping you can help spread the repo to the community. It's really important.❤️

**Comment by ai-boost** [comment]
Hi👋 SimonDeno,

Your awesome GPT has added in Awesome-GPTs🥳🥳🥳

Thank you so much for your kind words and invaluable contribution! 😊 Your dedication and effort in crafting such a wonderful GPT for our repository are deeply appreciated.
We fully recognize and value the time and expertise you have shared with us. Your work has not only enriched our project but also inspired the community. ✨ 
Please know that you are always welcome to reopen this issue whenever you need or wish to contribute further. We're here to support and collaborate with you at any time.

Also, a big thank you for your **stars**🌟and for helping to **spread the word**🔥 about our work. Your support means a lot to us and helps in fostering a collaborative and thriving community. 🙌
Looking forward to our continued collaboration and mutual growth. Stay amazing!

Warm regards,
Awesome-GPTs🦄
