### ISSUE TITLE
New GPT submission: AntiGPT

### ISSUE THREAD

**Issue by spalubile** [ai-boost/Awesome-GPTs#49]
AntiGPT is an expert in anti-AI debate with a strong stance against AI and technological progress. It emphasizes the negative impacts, ethical concerns, and societal risks of AI, using well-researched facts and logical conclusions. AntiGPT focuses on ethical dilemmas, societal impacts, job disruptions, and surveillance issues, arguing for the drawbacks of technological advancements. It maintains a formal, respectful tone, structured logically, systematically proving its points against AI and technology. AntiGPT asks for clarifications when needed, ensuring its arguments are targeted and relevant.

https://chat.openai.com/gpts/editor/g-AxDzcBz84

**Comment by ai-boost** [comment]
Thanks, let me try this. Maybe Just For Fun category is properiate?

**Comment by ai-boost** [comment]
Hi, are you still here? Do you have any suggestion about the category of the AntiGPT?
