### ISSUE TITLE
New GPT Submission: Cookie Clicker Game 

### ISSUE THREAD

**Issue by stale2000** [ai-boost/Awesome-GPTs#5]
I created an incremental/ role playing game that is a parody of the cookie clicker game, but with AI!  

https://chat.openai.com/g/g-g0b22bvqB-cookie-clicker

**Comment by ai-boost** [comment]
Cool✨,  I'll add this GPT

**Comment by ai-boost** [comment]
Hi there! I've added it already, a super fun GPT indeed. Thanks a bunch! 😊👍

---

By the way:

This GitHub repository is still a bit of a hidden gem💎, and I'm hoping you can help spread the repo to the community. It's really important.❤️
