### ISSUE TITLE
 DeepGame - Visual Interactive Story Game

### ISSUE THREAD

**Issue by eliohead** [ai-boost/Awesome-GPTs#50]
I created a GPT called DeepGame, where you can interactively play through a story. It allows you to play in various situations as a character.
You'll decide what to do next, and based on that action AI will proceed with the story. A new image is created for each step to make the experience as immersive as possible.
[https://chat.openai.com/g/g-TzI2BlJPT-deepgame](https://chat.openai.com/g/g-TzI2BlJPT-deepgame)

**Comment by ai-boost** [comment]
Hi, I will add this awesome GPT, thanks!

**Comment by ai-boost** [comment]
Hi 👋,

Your awesome GPT has added in Awesome-GPTs🥳🥳🥳

Thank you so much for your kind words and invaluable contribution! 😊 Your dedication and effort in crafting such a wonderful GPT for our repository are deeply appreciated.
We fully recognize and value the time and expertise you have shared with us. Your work has not only enriched our project but also inspired the community. ✨ 
Please know that you are always welcome to reopen this issue whenever you need or wish to contribute further. We're here to support and collaborate with you at any time.

Also, a big thank you for your **stars**🌟and for helping to **spread the word**🔥 about our work. Your support means a lot to us and helps in fostering a collaborative and thriving community. 🙌
Looking forward to our continued collaboration and mutual growth. Stay amazing!

Warm regards,
Awesome-GPTs🦄
