### ISSUE TITLE
Gantt Chart GPT

### ISSUE THREAD

**Issue by onlinegantt** [ai-boost/Awesome-GPTs#91]
This project management assistant can auto-generate an editable gantt chart from your project files

https://chat.openai.com/g/g-ihJfmYAJn-gantt-chart-gpt

Productivity

**Comment by ai-boost** [comment]
Hi, thanks for your GPT, I will add this😊

**Comment by ai-boost** [comment]
Hi [onlinegantt](https://github.com/onlinegantt),

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs
