### ISSUE TITLE
Submit New GPT: EconomicsGPT

### ISSUE THREAD

**Issue by dpeachpeach** [ai-boost/Awesome-GPTs#96]
EconomicsGPT is tailored for K-8, High school students, and Undergraduates studying Economics. Using high-quality instructional material from the internet, the University of Chicago's lectures, lecture notes, and course materials, EconomicsGPT allows students to receive high-quality personal tutoring in a subject that has primitive documentation online. EconGPT also holds a large bank of practice problems for prospective students to choose from. Just ask for a few!

[Use now](https://chat.openai.com/g/g-7McsRKuPS-economicsgpt)

**Comment by ai-boost** [comment]
Hi 👋, thanks for you GPT, I'll add this! 🎉

**Comment by ai-boost** [comment]
The awesome GPT has been added to Awesome-GPTs🎉

By the way, this GitHub repository is still a bit of a hidden gem, and I'm hoping you can help spread the repo to the community or your friends. It's really important.❤️

**Comment by ai-boost** [comment]
Hi [dpeachpeach](https://github.com/dpeachpeach),

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs
