### ISSUE TITLE
Debate Mentor

### ISSUE THREAD

**Issue by kylecoogan** [ai-boost/Awesome-GPTs#99]
Education
Mentor and debater, guides users to articulate conclusions.
https://chat.openai.com/g/g-KIX0IC8cj-debate-mentor

**Comment by ai-boost** [comment]
Thanks for your GPT❤️, any suggestion about the category of the GPT (maybe Education)?

**Comment by ai-boost** [comment]
Thanks for your GPT❤️, I will add this😊

**Comment by kylecoogan** [comment]
Thank you

**Comment by ai-boost** [comment]
Hi [kylecoogan](https://github.com/kylecoogan),

Thanks a ton for your contribution and support! 🌟 Your work with the GPT is highly appreciated. Remember, this issue can always be reopened for your valuable inputs.

Cheers for the star and spreading the word! 🚀

Best,
Awesome-GPTs
